name: Test API Code

on:
  pull_request:
    paths:
    - 'ec2Controller/**'
    - '.github/workflows/python-test.yml'

jobs:
  Unit-Test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
    
    # Tests
    - id: Test-code
      name: Python Tests
      run: |
        pip3 install -r ec2Controller/requirements.txt
        python3 ec2Controller/manage.py test   